version: "3"
services:
  sab-backend:
    build: .
    command: "rails s -b 0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - ".:/usr/src/app"
    env_file:
      - ./.env
    tty: true
    stdin_open: true

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  postgres: